### ISSUE TITLE
RDSマルチバイトをinsertすると ??? になる問題

### ISSUE THREAD

**Issue by Sugi275** [cndjp/qicoo-ansible#34]
RDSマルチバイトをinsertすると ??? になる問題

**Comment by Sugi275** [comment]
DB Parameter Groups を設定すると良さそう？
http://ria10.hatenablog.com/entry/20130619/1371603765

**Comment by nnao45** [comment]
あーDBのお決まりのそれですね、cloudformationよyaml作るかー
